config/routes.rb
Rails.application.routes.draw do

  resources :reviews
  resources :favorites, only: [:create, :destroy]
  resources :restaurants, only: [:index, :show]
  resources :users, except: [:index]

  root 'restaurants#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#new'
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_many :reviews
  has_many :favorites
  has_many :restaurants, through: :favorites

  validates :user_name, {presence: true, uniqueness: true}
  validates :name, presence: true
  validates :password, presence: true, on: :create
  validates :password, presence: true, on: :update, if: :password_changed?

  has_secure_password

## Used to check if password is provided when editing user for validation ##
  def password_changed?
    !password.blank?
  end

## Returns array of food types based on favorited restaurants ##
  def user_food_types(user)
    food_type_array = user.restaurants.map do |restaurant|
      restaurant.food_type.name
    end
  end

## Returns hash of food types and instance counts ##
  def food_type_count(array)
    counts = Hash.new(0)
    array.each do |key|
      counts[key] += 1
    end
    counts
  end

## Returns most liked food type or string if no favorites ##
  def favorite_food_type
    food_type_array = user_food_types(self)
    count_hash = food_type_count(food_type_array)
    favorite = count_hash.max_by{|k,v| v}
    if favorite == nil
      return "You don't have a favorite cuisine yet!"
    else
      return "#{favorite[0]}"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user, only: [:new, :create, :edit]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    @reviews = Review.where(user: @user)
  end

  def new
    @user = User.new
  end

  def create
    user = User.create(user_params)
    if user.valid?
      session[:user_id] = user.id
      redirect_to restaurants_path
    else
      flash[:message] = user.errors.full_messages
      redirect_to new_user_path
    end
  end

  # def edit
  # end

  def update
    if @user.update(user_params)
      redirect_to user_path(current_user)
    else
      flash[:message] = @user.errors.full_messages
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    Favorite.where(user: @user).destroy_all
    Review.where(user: @user).destroy_all
    @user.destroy
    session.clear
    redirect_to login_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :user_name, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => "reload" %>

<div class="view" id="user_edit">

  <% if flash[:message] %>
    <%= flash[:message] %>
  <% else %>
    <br>
  <% end %>

  <body class="text-center">
    <div class="form-signin" style="margin: auto; max-width: 330px; padding: 100px 0px 213px;">

      <h1 class="h3 mb-3 font-weight-normal">Edit</h1>

      <%= form_for @user do |f| %>

        <%= f.label :name, class: 'sr-only' %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :user_name, class: 'sr-only' %>
        <%= f.text_field :user_name, class: 'form-control' %>
        <br>
        <small class="form-text text-muted">Leave password blank to keep your old password</small>
        <%= f.label :password, class: 'sr-only' %>
        <%= f.password_field :password, :placeholder => "New Password", class: 'form-control' %>

        <%= f.label :password_confirmation, class: 'sr-only' %>
        <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation", class: 'form-control' %>
        <br>
        <%= f.submit "Edit", :class => 'btn btn-log btn-primary btn-block' %>
      <% end %>

    </div>
  </body>

app/views/users/index.erb
<%= form_for User.new, controller: 'users', action: 'create' do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :user_name %>
  <%= f.text_field :user_name %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit "Sign up" %>
<% end %>

app/views/users/new.html.erb
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => "reload" %>

<div class="view" id="user_intro">

  <% if flash[:message] %>
    <%= flash[:message] %>
  <% else %>
    <br>
  <% end %>

  <body class="text-center">
    <div class="form-signin" style="margin: auto; max-width: 330px; padding: 100px 0px 260px;">

      <h1 class="h3 mb-3 font-weight-normal">Sign Up</h1>

      <%= form_for User.new, controller: 'users', action: 'create' do |f| %>

        <%= f.label :name, class: 'sr-only' %>
        <%= f.text_field :name, :placeholder => "Name", class: 'form-control' %>

        <%= f.label :user_name, class: 'sr-only' %>
        <%= f.text_field :user_name, :placeholder => "Username", class: 'form-control' %>

        <%= f.label :password, class: 'sr-only' %>
        <%= f.password_field :password, :placeholder => "Password", class: 'form-control' %>

        <%= f.label :password_confirmation, class: 'sr-only' %>
        <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation", class: 'form-control' %>
        <br>
        <%= f.submit "Sign up", :class => 'btn btn-log btn-primary btn-block' %>
      <% end %>

    </div>
  </body>
</div>
<!-- form_for @order, :html => {:class => "foo"} -->

app/views/users/original_show.html.erb
<h1><%= @user.name %></h1>
<h3>AKA <%= @user.user_name %></h3>
<br>
<%= @user.favorite_food_type %><br>
You've written <%= pluralize(@user.reviews.count, 'review') %><br>
Member since <%= @user.created_at.strftime("%B %d, %Y") %><br>
<%= link_to "Edit", edit_user_path(@user) %> - <%= link_to "Delete", user_path(@user), method: :delete %>

<br><br>

<% if @reviews.count != 0 %>
  <h4>All Reviews</h4>
  <ul>
    <% @reviews.each do |review| %>
      <li>
        <b>Restaurant:</b> <%= review.restaurant.name %><br>
        <b>Rating:</b> <%= review.rating %><br>
        <b>Created:</b> <%= review.created_at.strftime("%B %d, %Y") %><br>
        <% if review.created_at != review.updated_at %>
          <b>Updated:</b> <%= review.updated_at.strftime("%B %d, %Y") %><br>
        <% end %>
        <%= review.content %><br>
        <%= link_to "Edit", edit_review_path(review) %> - <%= link_to "Delete", review_path(review), method: :delete %>
      </li><br>
    <% end %>
  </ul>
<% end %>

<% if @user.favorites.count != 0 %>
  <h4>Favorited Restaurants</h4>
  <ul>
    <% @user.favorites.each do |favorite| %>
      <li>
        <%= link_to favorite.restaurant.name, restaurant_path(favorite.restaurant) %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/users/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-4">
			<img class="profile_img" alt="Bootstrap Image Preview" src="https://images.unsplash.com/photo-1501869150797-9bbb64f782fd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80" />
		</div>
		<div class="col-md-8">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>
							True Name
						</th>
						<th>
							User Name
						</th>
						<th>
							Favorite Food
						</th>
            <th>
              Number of Reviews Written
            </th>
						<th>
							Member Since
						</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							<%= @user.name %>
						</td>
						<td>
							<%= @user.user_name %>
						</td>
						<td>
							<%= @user.favorite_food_type %>
						</td>
            <td>
              <%= @user.reviews.count %>
            </td>
						<td>
							<%= @user.created_at.strftime("%B %d, %Y") %>
						</td>
					</tr>
				</tbody>
			</table>
      <%= link_to "Edit", edit_user_path(@user) %> - <%= link_to "Delete", user_path(@user), method: :delete %>
		</div>
	</div>

	<div class="row">
    <div class="col-md-4">
      <h3>Favorited Restaurants</h3>
      <hr>
      <% if @user.favorites.count != 0 %>
        <ul>
          <% @user.favorites.each do |favorite| %>
            <li>
              <%= link_to favorite.restaurant.name, restaurant_path(favorite.restaurant) %>
            </li>
          <% end %>
        </ul>
        <% else %>
        <h4>You do not have any favorited restaurants.</h4>
      <% end %>
    </div>
		<div class="col-md-8">
      <h3>Reviews Written</h3>
      <hr>
      <% if @reviews.count != 0 %>
        <ul>
          <% @reviews.each do |review| %>
            <li>
              <b>Restaurant:</b> <%= link_to review.restaurant.name, restaurant_path(review.restaurant) %><br>
              <b>Rating:</b> <%= review.rating %><br>
              <b>Created:</b> <%= review.created_at.strftime("%B %d, %Y") %><br>
              <% if review.created_at != review.updated_at %>
                <b>Updated:</b> <%= review.updated_at.strftime("%B %d, %Y") %><br>
              <% end %>
              <%= review.content %><br>
              <%= link_to "Edit", edit_review_path(review) %> - <%= link_to "Delete", review_path(review), method: :delete %>
            </li><br>
          <% end %>
        </ul>
        <% else %>
        <h4>You have not written any reviews.</h4>
      <% end %>
		</div>
	</div>
</div>