config/routes.rb
Rails.application.routes.draw do

  resources :reviews
  resources :favorites, only: [:create, :destroy]
  resources :restaurants, only: [:index, :show]
  resources :users, except: [:index]

  root 'restaurants#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#new'
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  has_many :favorites
  has_many :reviews
  has_many :users, through: :favorites
  belongs_to :food_type

  def self.search(search)
    if search
       food_type = FoodType.where("LOWER(name) LIKE ?", "%#{search.downcase}%")
      if food_type
        self.where(food_type: food_type)
      else
        Restaurant.all
      end
    else
      Restaurant.all
    end
  end

  def self.apply_price_filter(params, array)
    criteria = params["price_range"].reject { |p| p.empty? }
    final_result = []
    if !criteria.empty?
      criteria.each do |price_range|
        result = array.where("price_range = ?", price_range.to_i)
        final_result.push(result).flatten!
      end
      final_result
    else
      array
    end
  end

  def self.apply_rating_filter(params, array)
    criteria = params["rating"]
    final_result = []
    reviews = Hash.new(0)
    array.each do |restaurant|
      reviews[restaurant] = Review.avg_rating(restaurant)
    end
    filtered = reviews.select{ |k,v| v >= criteria[0].to_i}
    filtered_array = []
    filtered.each do |restaurant, rating|
      filtered_array << restaurant
    end
    filtered_array
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user
  helper RestaurantsHelper

  def index
    if params[:search]
      search_criteria = params["search"]
      price_criteria = params["restaurant"]["price_range"].reject { |p| p.empty? }
      rating_criteria = params["restaurant"]["rating"]
      if !search_criteria.empty?
        search_results = Restaurant.search(params[:search])
        if price_criteria.empty? && rating_criteria.empty?
          @restaurants = search_results
        else
          restaurants_filter_by_price = Restaurant.apply_price_filter(params[:restaurant], search_results)
          @restaurants = Restaurant.apply_rating_filter(params[:restaurant], restaurants_filter_by_price)
        end
      elsif !price_criteria.empty? || !rating_criteria.empty?
        search_results = Restaurant.all
        restaurants_filter_by_price = Restaurant.apply_price_filter(params[:restaurant], search_results)
        @restaurants = Restaurant.apply_rating_filter(params[:restaurant], restaurants_filter_by_price)
      else
        @restaurants = Restaurant.all
      end
      @message = true
    else
      @restaurants = Restaurant.all
    end
    @user = current_user
    @price_range = [1, 2, 3]
    @rating = [1, 2, 3, 4, 5]
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
    @user = current_user
    @reviews = Review.where(restaurant: @restaurant)
    @favorite = Favorite.find_by(restaurant: @restaurant, user: @user)
    @rating = [1, 2, 3, 4, 5]
    @photo = RestaurantsHelper.fetch_photo(@restaurant)
  end

end

app/helpers/restaurants_helper.rb
module RestaurantsHelper

## ------------------------- PHOTO URLs -------------------------- ##
  @@american_food_photos = [
    "https://images.unsplash.com/photo-1535381987-2075e3077deb?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=334&amp;q=80 334w",
    "https://images.unsplash.com/photo-1515669097368-22e68427d265?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1489391013510-49401c8a3b6c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1517984055083-fd6e1e788e54?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80",
    "https://images.unsplash.com/photo-1475474369946-72bb667aae19?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=640&q=80"
  ]

  @@asian_food_photos = [
    "https://images.unsplash.com/photo-1503764654157-72d979d9af2f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1053&q=80",
    "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1532347231146-80afc9e3df2b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=632&q=80",
    "https://images.unsplash.com/photo-1534256958597-7fe685cbd745?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80",
    "https://images.unsplash.com/photo-1528510138849-786a5feddf94?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80"
  ]

  @@bakeries_photos = [
    "https://images.unsplash.com/photo-1454641350786-bc31a1997ba9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1551500693-f3e9e7842948?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1491778589563-419a091ecd26?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1549571448-958194cb23cb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1525904971217-668a1229f701?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"
  ]

  @@food_truck_photos = [
    "https://images.unsplash.com/photo-1509315811345-672d83ef2fbc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80",
    "https://images.unsplash.com/photo-1519861155730-0b5fbf0dd889?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=863&q=80",
    "https://images.unsplash.com/photo-1513640127641-49ba81f8305c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1530649325239-1c2ebf1e3f07?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/reserve/DHHQbqc0RrWVf0uDNe5E_The%20Litte%20Cafe.jpg?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1189&q=80"
  ]

  @@italian_food_photos = [
    "https://images.unsplash.com/photo-1534649643822-e7431de08af6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=679&q=80",
    "https://images.unsplash.com/photo-1536964549204-cce9eab227bd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80",
    "https://images.unsplash.com/photo-1505932049984-db368d92fa63?ixlib=rb-1.2.1&auto=format&fit=crop&w=676&q=80",
    "https://images.unsplash.com/photo-1522666257812-173fdc2d11fe?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=675&q=80",
    "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80"
  ]

  @@mexican_food_photos = [
    "https://images.unsplash.com/photo-1536792058-e4c673a9c11f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80",
    "https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?ixlib=rb-1.2.1&auto=format&fit=crop&w=675&q=80",
    "https://images.unsplash.com/photo-1464219222984-216ebffaaf85?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjUwOTAwfQ&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?ixlib=rb-1.2.1&auto=format&fit=crop&w=675&q=80",
    "https://images.unsplash.com/photo-1536791985-e156f3dbbb9c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80"
  ]

  @@bar_photos = [
    "https://images.unsplash.com/photo-1468072114808-903e572b8ead?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=966&q=80",
    "https://images.unsplash.com/photo-1514933651103-005eec06c04b?ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80",
    "https://images.unsplash.com/photo-1497644083578-611b798c60f3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1470337458703-46ad1756a187?ixlib=rb-1.2.1&auto=format&fit=crop&w=1049&q=80",
    "https://images.unsplash.com/photo-1491333078588-55b6733c7de6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"
  ]

  @@spanish_food_photos = [
    "https://images.unsplash.com/photo-1515443961218-a51367888e4b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1542904990-d60f68e9af4e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1524932326868-56e1f1ede465?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80",
    "https://images.unsplash.com/photo-1516721049043-66daa54ed3cd?ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80",
    "https://images.unsplash.com/photo-1500482176473-ccba10e1e880?ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80"
  ]

  @@seafood_photos = [
    "https://images.unsplash.com/photo-1448043552756-e747b7a2b2b8?ixlib=rb-1.2.1&auto=format&fit=crop&w=949&q=80",
    "https://images.unsplash.com/photo-1542790246-93eacdb8f756?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1475905760530-a22eda0fb1b3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1054&q=80",
    "https://images.unsplash.com/photo-1515443961218-a51367888e4b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80"
  ]

  @@sandwich_photos = [
    "https://images.unsplash.com/photo-1485451456034-3f9391c6f769?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1053&q=80",
    "https://images.unsplash.com/photo-1509722747041-616f39b57569?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1543616153-d69a13f346ad?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1481070414801-51fd732d7184?ixlib=rb-1.2.1&auto=format&fit=crop&w=925&q=80"
  ]

  @@french_food_photos = [
    "https://images.unsplash.com/photo-1462837019796-6f0204b48d95?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1477747219299-60f95c811fef?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1464306076886-da185f6a9d05?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80",
    "https://images.unsplash.com/photo-1464500650248-1a4b45debb9f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1161&q=80"
  ]

  @@misc = "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80"

## ----------------------- FOOD TYPE ARRAY ----------------------- ##
  @@asian_foods = ["Korean", "Japanese", "Vietnamese", "Taiwanese", "Thai", "Poke", "Sushi Bars", "Asian Fusion", "Chinese"]

  @@american_foods = ["American (New)", "American (Traditional)", "Burgers", "Barbeque", "Hot Dogs", "Southern", "Chicken Wings"]

  @@bakeries_cafe = ["Breakfast & Brunch", "Bakeries", "Cafes", "Coffee & Tea"]

  @@food_trucks = ["Food Stands", "Street Vendors", "Food Trucks"]

  @@italian_foods = ["Pizza", "Italian"]

  @@mexican_foods = ["Mexican"]

  @@bars = ["Beer Bar", "Cocktail Bars", "Pubs", "Bars", "Sports Bars", "Beer, Wine & Spirits", "Sports Clubs"]

  @@spanish_foods = ["Tapas/Small Plates", "Argentine", "Spanish"]

  @@seafood = ["Seafood", "Seafood Markets"]

  @@sandwiches = ["Sandwiches"]

  @@french_foods = ["French"]

## ------------------------- METHOD ------------------------------ ##
    def self.fetch_photo(restaurant)
      num = rand(0..4)
      type = restaurant.food_type.name
      if @@asian_foods.include?(type)
        @@asian_food_photos[num]
      elsif @@american_foods.include?(type)
        @@american_food_photos[num]
      elsif @@bakeries_cafe.include?(type)
        @@bakeries_photos[num]
      elsif @@food_trucks.include?(type)
        @@food_truck_photos[num]
      elsif @@italian_foods.include?(type)
        @@italian_food_photos[num]
      elsif @@mexican_foods.include?(type)
        @@mexican_food_photos[num]
      elsif @@bars.include?(type)
        @@bar_photos[num]
      elsif @@spanish_foods.include?(type)
        @@spanish_food_photos[num]
      elsif @@seafood.include?(type)
        @@seafood_photos[num]
      elsif @@sandwiches.include?(type)
        @@sandwich_photos[num]
      elsif @@french_foods.include?(type)
        @@french_food_photos[num]
      else
        @@misc
      end
    end

end

app/views/restaurants/index.html.erb
<% stylesheet_link_tag 'application' %>

<!--------------- Header --------------------->
<div class="container-fluid">
  <div class="row">
    <div class="col" id="header">
      <h1 class="cover-heading">
        Restaurants
        <small class="text-muted">near 4th Ave WeWork</small>
      </h1>
    </div>
  </div>
</div>

<!--------------- Search Form --------------------->
<div class="container">
  <div class="row">
    <div class="col" id="header">
      <form class="form" role="form">
        <%= form_tag(restaurants_path, method: :get) do %>
          <%= text_field_tag :search, params[:search], class: 'form-control mb-2 mr-sm-2', placeholder: "Search by Cuisine" %>

          <%= label_tag "Price Range " %>
          <%= collection_check_boxes :restaurant, :price_range, @price_range, :itself, :itself %>

          <%= label_tag "Rating (Equal to and Higher than)" %>
          <%= collection_select :restaurant, :rating, @rating, :itself, :itself , :class => "result_row" %>

          <div class="input-group-append submit_button">
          <%= submit_tag "Search", class: 'btn btn-primary mx-auto' %>
          </div>
        <% end %>
      </form>
    </div>
  </div>
</div>

<!--------------- Result Message -------------------------->
<div class="container">
  <div class="row" id="result_row">
    <div class="col-md-2">
      <% if @message %>
        <%= pluralize(@restaurants.count, 'result') %>
      <% else %>
        <br>
      <% end %>
    </div>
  </div>
</div>

<!--------------- List of Restaurants -------------------------->
<div class="container">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h5 class="card-title"><%= link_to restaurant.name, restaurant_path(restaurant) %></h5>
          </div>
          <div class="card-body">
            <h6 class="card-subtitle mb-2 text-muted">Price Range: <%= restaurant.price_range %></h6>
            <h6 class="card-subtitle mb-2 text-muted">Cuisine: <%= restaurant.food_type.name %></h6>
            <h6 class="card-subtitle mb-2 text-muted">Rating: <%= Review.avg_rating(restaurant) %> (Based on <%= pluralize(restaurant.reviews.count, 'review') %>)</h6>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => "reload" %>

<% if flash[:message] %>
  <%= flash[:message] %>
<% end %>


<div class="container-fluid">

	<div class="row">
		<div class="col-md-12">
			<h3>
				<%= @restaurant.name %>
			</h3>
		</div>
	</div>

	<div class="row">
		<div class="col-md-4">
      <img class="profile_img" src=<%= @photo %> class="img-fluid" alt="...">
		</div>

<!-------------- Restaurant Info  -------------->
		<div class="col-md-4">
			<dl>
        <dt> Cuisine </dt>
				<dd> <%= @restaurant.food_type.name %> </dd>

				<dt> Address </dt>
				<dd> <%= @restaurant.address %> </dd>

				<dt> Price Range (0-3) </dt>
				<dd> <%= @restaurant.price_range %> </dd>

				<dt> Rating </dt>
				<dd> <%= Review.avg_rating(@restaurant) %> </dd>

        <% if @favorite %>
          <%= link_to 'Unfavorite', favorite_path(@favorite), method: :delete, :class => "btn btn-danger" %>
        <% else %>
          <%= link_to "Favorite", favorites_path(restaurant: @restaurant), method: :post, :class => "btn btn-primary" %>
        <% end %>
			</dl>
		</div>

<!-------------- Review Form if logged in  -------------->
		<div class="col-md-4">
      <% if logged_in? %>
        <dl>
          <%= form_for Review.new, :html => {:class => "form-group"}, :url => reviews_path do |f| %>
            <dt> Write a review </dt>
    				<dd> <%= f.text_area :content, :class => "col", :style =>"height: 150px"%> </dd>

            <dt> Rating <%= f.collection_select :rating, @rating, :itself, :itself %> </dt>
            <dd>
            <%= f.hidden_field :user_id, :value => @user.id %>
            <%= f.hidden_field :restaurant_id, :value => @restaurant.id %>
            </dd>
            <%= f.submit "Post Review", :class => "btn btn-primary"%>
          <% end %>
        </dl>
      <% end %>
		</div>

	</div>

<!---------- Prints out review count if there are any ---------->
	<div class="row">
		<div class="col-md-4 border border-1">
      <% if @reviews.any? %>
        <div class="">
          <b>Reviews: </b><%= @reviews.count %>
        </div>
      <% end %>
    </div>
  </div>
<br>
<!---------- Prints out reviews if there are any ---------->
  <div class="row">
    <div class="col-md-8 border border-1">
      <% if @reviews.any? %>
        <dl>
          <% @reviews.each do |review| %>
            <dt> User: <%= review.user.name %> </dt>
            <dd> Rating: <%= review.rating %><br>
            Created: <%= review.created_at.strftime("%B %d, %Y") %><br>

              <% if review.created_at != review.updated_at %>
                Updated: <%= review.updated_at.strftime("%B %d, %Y") %>
              <% end %>
            </dd>
            <dd> <%= review.content %> </dd><br>
          <% end %>
        </dl>
      <% end %>
    </div>
  </div>

</div>